site_name: Sample of MkDocs Material Documentation
site_url: https://bismus-le-sha.github.io/python_mkdocs/
site_author: Alexey Bismus

# theme:
#   name: material
#   language: en
theme:
  name: null
  custom_dir: theme

  font:
    text: Roboto
    code: Fira Code

  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: indigo
      accent: pink

    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: teal
      accent: lime

  features:
    - search.suggest

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Custom Theme: custom-theme-guid.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bismus-le-sha
extra_css:
  - css/index.css
extra_javascript:
  - js/custom.js
